name: Goreleaser Snapshot Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run Goreleaser Snapshot
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
        env:
          GORELEASER_CURRENT_TAG: snapshot # Goreleaser 会用这个作为版本信息的一部分

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: goreleaser-snapshot-build
          path: dist/*
          retention-days: 90